### ISSUE TITLE
Badge theming and styling didn't work with Vaadin 23.0

### ISSUE THREAD

**Issue by karstenlehmann** [TatuLund/badge#1]
The badge component didn't react to the given themes and variants with Vaadin 23.0.2

**Comment by TatuLund** [comment]
I can confirm this. Something has changed how one should import the badge styles in Vaadin 23 vs Vaadin 14

**Comment by TatuLund** [comment]
The original code did not show any error in Vaadin 23. I would assume that it should work, and the fact it does not work is probably a bug in Vaadin 23.
 
However I refactored the add-on to be web component wrapper and imported the styles in the web component and it seems to work well that way.

Use version 2.0.0 with Vaadin 23. Java API is unchanged.

**Comment by karstenlehmann** [comment]
I can confirm - it works now. Thank you
