### ISSUE TITLE
Badges have two layers of background

### ISSUE THREAD

**Issue by HerbertsVaadin** [TatuLund/badge#4]
This is on Vaadin 24. 
![image](https://github.com/TatuLund/badge/assets/80950643/115c128d-578b-494f-b2b6-a0bbf54476a3)

looks like it badge styling applies on the outer element as well, based on theme
![image](https://github.com/TatuLund/badge/assets/80950643/c35e9c2c-75f5-44c0-83f8-05cd98c77b05)
![image](https://github.com/TatuLund/badge/assets/80950643/8f900a21-61f3-4a4b-8e7a-81678dd1be1f)

I think if the badge is inside the shadowdom (and no badge styling imported for that shadowdom) then it applies properly only on the inner level. 
It was nice when it was just the `span` element in the version `1.0.0`, but I guess it didn't work for v23?

```java 
new Badge("3")
```

**Comment by TatuLund** [comment]
Yes. For me this looks intentional based on the imported styles. I.e. it is not a fault of the add-on. But it is change in Vaadin 24.1. I will add API to disable the feature as you pointed it is not nice in all cases.

**Comment by TatuLund** [comment]
Try out version 2.4.0

**Comment by HerbertsVaadin** [comment]
Solved with 2.4.0! Thanks!
